server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rowers_hub?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    properties:
      temp:
        use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.MySQLDialect
