CREATE TABLE users
(
    user_id  INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE user_squads
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    squad   ENUM('WOMENS', 'DEVELOPMENT', 'MENS') NOT NULL,
    level   ENUM('DEVELOPMENT', 'NOVICE', 'INTERMEDIATE', 'SENIOR') NOT NULL
);

CREATE TABLE user_creation_codes(
  id INT AUTO_INCREMENT PRIMARY KEY,
  creation_code VARCHAR(36) UNIQUE NOT NULL
);