name: run PR checks

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: crm  # This ensures the `crm` database is created if it doesn't exist
        ports:
          - 3306:3306  # Expose MySQL on port 3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests with Maven
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://mrc-crm-mysql:3306/crm?createDatabaseIfNotExist=true  # Ensure the JDBC URL is correctly set
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: rootpassword